# Generated by Django 6.0.4 on 2026-04-22 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=160)),
                ('contact_person', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerShortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='LinkAround_main.employerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='business_fields',
            field=models.ManyToManyField(related_name='employers', to='LinkAround_main.fieldpreference'),
        ),
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('degree', models.CharField(max_length=160)),
                ('location', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('portfolio_file', models.FileField(upload_to='portfolios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seekers', to='LinkAround_main.fieldpreference')),
            ],
        ),
        migrations.CreateModel(
            name='SeekerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shortlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='LinkAround_main.employershortlist')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='LinkAround_main.seekerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='employershortlist',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='LinkAround_main.seekerprofile'),
        ),
        migrations.AddConstraint(
            model_name='employershortlist',
            constraint=models.UniqueConstraint(fields=('employer', 'seeker'), name='unique_employer_seeker_shortlist'),
        ),
    ]
