# Generated by Django 6.0.4 on 2026-05-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkAround_main', '0002_employerprofile_user_seekerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='allow_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
